### PR TITLE
if host is ::, replace with localhost so that server.js logs out a working link …

### LINKED ISSUE #178: server address logged out isn't valid
when I run `node server.js` I see:

`Bl.ock Builder listening at http://:::8889`

blockbuilder is actually running over at `http://localhost:8889/`

### PR DESCRIPTION
**Pull request by micahstubbs**
…for local development.  fixes #178 

#### before

screen shot 2016-09-24 at 11 36 00 am

#### after

screen shot 2016-09-24 at 11 41 16 am

### CODE REVIEW

**Comment by micahstubbs** [comment]
will merge this, since it got the approval from @pavelloz 

this is a bit different from the git workflow I'm used to, where the reviewer will usually either merge or close a PR. will write this comment here just in case this is somehow different than what @enjalot whats to normally do 😄

**Comment by leitzler** [comment]
Just as a note, this is probably not a good idea. The "::" is IPv6 (representation of 0.0.0.0 in IPv4). So http://:::8889 is indeed a valid URI.

**Comment by pavelloz** [comment]
When im testing locally 0.0.0.0 takes me to `localhost`, so Im assuming its not such a big of a deal, to have `::` / `0.0.0.0` showing as `localhost` even if its not **always** the case. Probably everyone with custom config understands how to get to the localhost on their machine.

I still vote that it is better to have `localhost` over `::` -- one of them more often than not looks like a bug and can create confusion.

**Comment by leitzler** [comment]
But it is different things, localhost is 127.0.0.1 while 0.0.0.0 is "all interfaces", a huge difference. That is in IPv4.
In IPv6, localhost is ::1 and 0.0.0.0 is ::. It will be far more confusing to show incorrect information that misleads the user to think that the server isn't exposed on all ports (which it is).

So, if you want to avoid the "::" notation I strongly suggest you disable IPv6 on your host instead.

**Comment by micahstubbs** [comment]
@leitzler thanks for the comments.  would you say displaying`http://0.0.0.0:8889`is an improvement over displaying `http://localhost:8889` ? (even if  stops short of disabling IPv6)

**Comment by leitzler** [comment]
The correct way to do it (in case you do not want to support IPv6 at all) would be to pass the interface IP when you create the server. (see [API docs](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)).

Use '0.0.0.0' as hostname if you want the server to listen on all interfaces (others can connect), or use '127.0.0.1' if you want the server to only listen to 'localhost'. Then it won't be reachable from any other machine :).

**Comment by micahstubbs** [comment]
this address resolves for me as well when I paste it into Chrome `http://[::]:8889/`

**Pull request merged**
