### PR TITLE
put the DOCTYPE at the top of the compiled index.html for the user

### LINKED ISSUE #192: Renderer doesn't include DOCTYPE
I've been hunting down an odd CSS-related issue, where the rendering within blockbulder and the bl.ocks website differs. I've managed to boil it down to block builder omitting the DOCTYPE. 

This block simply renders a big red square:

```
<!DOCTYPE html>
<div style="height:100%; background-color: red"/>
```

In block builder you can see the square filling the screen:

http://blockbuilder.org/ColinEberhardt/bcecc04f27f62acdf44fd350e166b24d

Whereas on the blocks website, the div has a height of zero:

https://bl.ocks.org/ColinEberhardt/bcecc04f27f62acdf44fd350e166b24d

Looking at the difference in the rendered output, here it is from bl.ocks:

image

And here is the iframe contents from block builder:

image

The difference is the lack of HTML5 DOCTYPE. I have confirmed that omitting the DOCTYPE from a HTML document has this effect,.

### PR DESCRIPTION
**Pull request by micahstubbs**
fix #192 

**before**
screen shot 2017-05-04 at 3 30 13 pm

**after**
screen shot 2017-05-04 at 3 53 24 pm

### CODE REVIEW

**Comment by micahstubbs** [comment]
@enjalot could you review this PR when you have a moment?

**Comment by micahstubbs** [comment]
@pavelloz may be able to review this one as well.  it's a pretty small change. details in issue https://github.com/enjalot/blockbuilder/issues/192

**Comment by micahstubbs** [comment]
🎉

**Comment by curran** [comment]
Nice! Hoping I can find some time to submit a PR for adopting magic-sandbox, and also incorporate this change over there too.

**Pull request merged**
