### PR TITLE
update handlebars config in server.js.  fix #234

### LINKED ISSUE #234: no such file main.handlebars with node v12.3.0
no such file main.handlebars with node v12.3.0

`Error: ENOENT: no such file or directory, open '/Users/m/workspace/blockbuilder/views/layouts/main.handlebars'`

It looks like this is a known issue with handlebars.  I was able to adapt the fix mentioned in this 2017 github comment to fix this, and enable us to run on the latest nodejs, node v12.3.0

https://github.com/ericf/express-handlebars/issues/195#issuecomment-302112955
Screen Shot 2019-05-21 at 10 38 35 PM

### PR DESCRIPTION
**Pull request by micahstubbs**
This PR updates the way that we tell handlebars where to look for the main or base template.  It fixes a bug that appears when we try to run blockbuilder on node v12.3.0.  (the current latest nodejs).

This PR also unblocks the [nice work](https://github.com/enjalot/blockbuilder-search/pull/88) that @hydrosquall has been doing on in the [blockbuilder-search](https://github.com/enjalot/blockbuilder-search) UI repo to update our dependencies there and improve developer experience 😄 

fix #234 

## steps to test

```bash
# if you haven't already, first install nvm https://github.com/nvm-sh/nvm
# then install the latest nodejs
nvm install 12.3.0
```

then

```bash
cd blockbuilder
yarn 
yarn buildWatch

# open a new terminal window
cd ../blockbuilder-search
yarn
yarn buildWatch

# open another new terminal window
cd blockbuilder
node server.js
```

then make sure that both local blockbuilder and local blockbuilder-search render by visiting them in the browser:

http://localhost:8889/
http://localhost:8889/search

### CODE REVIEW

**Comment by micahstubbs** [comment]
## before 

Screen Shot 2019-05-21 at 10 43 22 PM

**Comment by micahstubbs** [comment]
## after

after-Screen Shot 2019-05-21 at 10 42 48 PM

**Comment by pavelloz** [comment]
When i tried to `yarn`, node-sass (in particular fsevents) threw me a lot of weird compiling errors.

It supposed to be fixed in 4.12.0 ( https://github.com/sass/node-sass/issues/2632 ) so i would recommend upgrade of that dependency.

When i changed it to 4.12.0 in package.json and tried again it didnt help, but i dont know how to use `yarn` - maybe it requires some additional action.

`npm install node-sass` worked like a charm, `yarn add node-sass` breaks.

Note: Im using fnm not nvm, but i assume its not a problem :)

**Comment by hydrosquall** [comment]
I suspect that yarn installing node-sass errored because it was installing
the version specified in yarn.lock, whereas npm succeeded because there was
no package-lock.json to make it reinstall the old version.

Note there is an issue with node-sass and this project in #233 that
upgrading to 4.12.0 may solve as well (this might be the fsevents error you
ran into).

**Comment by micahstubbs** [comment]
thanks for the reviews @pavelloz @hydrosquall @enjalot 🙏 

hopefully @hydrosquall is right and upgrading can resolve this node-sass compiling pain 😅

**Pull request merged**
